omit URL's password when stringifying URL for segment name
aws/aws-xray-sdk-go pull request #422
Opened 2023-10-10 10:15 UTC by aloababa

*Issue #421*

*Description of changes:*

Stripping basic auth password from url to avoid leak in xray traces.

2023-10-17 16:22 UTC, atshaw43 commented
Can you add some unit tests for this?

2023-10-19 08:49 UTC, aloababa commented
I've added TestRoundTripWithBasicAuth unit test.

2023-10-23 21:13 UTC, atshaw43 requested changes

2023-10-23 21:13 UTC, atshaw43 commented on xray/client_test.go
> +		assert.Equal(t, stripURL(*u), subseg.HTTP.Request.URL)
We are testing the function against the function. We are not really testing if the functionality works. Let's test the output against a source of truth.

```suggestion
		assert.Equal(t, "http://user:***@127.0.0.1:"+u.Port(), subseg.HTTP.Request.URL)
```

2023-10-24 15:46 UTC, aloababa commented
I've updated the pull request.

Thanks for the response.

2023-10-24 16:25 UTC, atshaw43 approved these changes

2023-10-25 17:36 UTC, atshaw43 commented
You will need to rebase with the upstream to merge this.

2023-10-26 10:22 UTC, aloababa commented
I rebased on master.

2023-10-27 16:31 UTC, merged

2023-10-27 17:46 UTC, wangzlei reviewed
LGTM